
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required

before_install:
  - sudo apt-get install smlnj
  - sudo apt-get install ml-yacc

script:
  - echo -n | sml Tests/sources.sml
